var c=document.createElement("iframe");
c.id="js-calculator-iframe";
c.src="https://nicolaschan.com/js-calculator/";
c.style.background="#ffffff";
c.width="40%"; 
c.height="30%"; 
c.frameBorder="0"; 
c.style.border="2px solid #cccccc"; 
c.style.position="absolute"; 
c.style.top="20px"; 
c.style.right="20px"; 
document.body.appendChild(c); 